%YAML:1.0
---
path: ../../../
root_name: pdense1
option_name: option-0000
max_num: 30
is_PCD: 1
is_global: 1
option:
  head: 0
  level: 0
  csize: 2
  threshold: 0.6
  wsize: 7
  minImageNum: 2
  CPU: 8
  setEdge: 0
  useBound: 0
  useVisData: 0
  sequence: -1
  maxAngle: 6
  quad: 2.5